### ISSUE TITLE
Write a vignette for the new XH compartment models

### ISSUE THREAD

**Issue by smitdave** [dd-harp/ramp.library#28]
The article should discuss:

The reason for compartmental models
Verification and testing

- [x] SIS, 
- [x] SIP, 
- [x] SIR, 
- [x] SIRS, 
- [x] SEIR, 
- [x] SEIRV

**Comment by smitdave** [comment]
Currently assigned to both Doreen and Juliet. Only one needs to take on the issue.

**Comment by Jnsumba** [comment]
On the vignette of the models SIR, SIRS, SEIR, SEIRV,  without demography terms, 

- The equilibrium for SIRS  is found and tested. 
- Could not find the equilibrium for SEIR and SIR and SEIRV 
- These could be modified to SEIRS and SEIRVS if no demography terms are considered else their vignettes could be written without  steady states

**Comment by smitdave** [comment]
This vignette needs to do a few things:
+ discuss verification for the models
+ introduce through examples how to use them
